/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PretentiousRouteImport } from './routes/pretentious'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PretentiousIndexRouteImport } from './routes/pretentious.index'
import { Route as ThemeImportRouteImport } from './routes/theme.import'
import { Route as PretentiousUsersRouteImport } from './routes/pretentious.users'
import { Route as PretentiousSupportRouteImport } from './routes/pretentious.support'
import { Route as PretentiousLandingRouteImport } from './routes/pretentious.landing'
import { Route as PretentiousBillingRouteImport } from './routes/pretentious.billing'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthProfileConnectionsRouteImport } from './routes/_auth.profile.connections'
import { Route as AuthWWorkspaceIdIndexRouteImport } from './routes/_auth.w.$workspaceId.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthWWorkspaceIdAdminRouteImport } from './routes/_auth.w.$workspaceId.admin'
import { Route as AuthWWorkspaceIdDDmIdRouteImport } from './routes/_auth.w.$workspaceId.d.$dmId'
import { Route as AuthWWorkspaceIdCChannelIdRouteImport } from './routes/_auth.w.$workspaceId.c.$channelId'

const PretentiousRoute = PretentiousRouteImport.update({
  id: '/pretentious',
  path: '/pretentious',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PretentiousIndexRoute = PretentiousIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PretentiousRoute,
} as any)
const ThemeImportRoute = ThemeImportRouteImport.update({
  id: '/theme/import',
  path: '/theme/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PretentiousUsersRoute = PretentiousUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PretentiousRoute,
} as any)
const PretentiousSupportRoute = PretentiousSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PretentiousRoute,
} as any)
const PretentiousLandingRoute = PretentiousLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => PretentiousRoute,
} as any)
const PretentiousBillingRoute = PretentiousBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PretentiousRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileConnectionsRoute = AuthProfileConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthProfileRoute,
} as any)
const AuthWWorkspaceIdIndexRoute = AuthWWorkspaceIdIndexRouteImport.update({
  id: '/w/$workspaceId/',
  path: '/w/$workspaceId/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthWWorkspaceIdAdminRoute = AuthWWorkspaceIdAdminRouteImport.update({
  id: '/w/$workspaceId/admin',
  path: '/w/$workspaceId/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWWorkspaceIdDDmIdRoute = AuthWWorkspaceIdDDmIdRouteImport.update({
  id: '/w/$workspaceId/d/$dmId',
  path: '/w/$workspaceId/d/$dmId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWWorkspaceIdCChannelIdRoute =
  AuthWWorkspaceIdCChannelIdRouteImport.update({
    id: '/w/$workspaceId/c/$channelId',
    path: '/w/$workspaceId/c/$channelId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/pretentious': typeof PretentiousRouteWithChildren
  '/profile': typeof AuthProfileRouteWithChildren
  '/pretentious/billing': typeof PretentiousBillingRoute
  '/pretentious/landing': typeof PretentiousLandingRoute
  '/pretentious/support': typeof PretentiousSupportRoute
  '/pretentious/users': typeof PretentiousUsersRoute
  '/theme/import': typeof ThemeImportRoute
  '/pretentious/': typeof PretentiousIndexRoute
  '/profile/connections': typeof AuthProfileConnectionsRoute
  '/w/$workspaceId/admin': typeof AuthWWorkspaceIdAdminRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/w/$workspaceId/': typeof AuthWWorkspaceIdIndexRoute
  '/w/$workspaceId/c/$channelId': typeof AuthWWorkspaceIdCChannelIdRoute
  '/w/$workspaceId/d/$dmId': typeof AuthWWorkspaceIdDDmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthProfileRouteWithChildren
  '/pretentious/billing': typeof PretentiousBillingRoute
  '/pretentious/landing': typeof PretentiousLandingRoute
  '/pretentious/support': typeof PretentiousSupportRoute
  '/pretentious/users': typeof PretentiousUsersRoute
  '/theme/import': typeof ThemeImportRoute
  '/pretentious': typeof PretentiousIndexRoute
  '/profile/connections': typeof AuthProfileConnectionsRoute
  '/w/$workspaceId/admin': typeof AuthWWorkspaceIdAdminRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/w/$workspaceId': typeof AuthWWorkspaceIdIndexRoute
  '/w/$workspaceId/c/$channelId': typeof AuthWWorkspaceIdCChannelIdRoute
  '/w/$workspaceId/d/$dmId': typeof AuthWWorkspaceIdDDmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/pretentious': typeof PretentiousRouteWithChildren
  '/_auth/profile': typeof AuthProfileRouteWithChildren
  '/pretentious/billing': typeof PretentiousBillingRoute
  '/pretentious/landing': typeof PretentiousLandingRoute
  '/pretentious/support': typeof PretentiousSupportRoute
  '/pretentious/users': typeof PretentiousUsersRoute
  '/theme/import': typeof ThemeImportRoute
  '/pretentious/': typeof PretentiousIndexRoute
  '/_auth/profile/connections': typeof AuthProfileConnectionsRoute
  '/_auth/w/$workspaceId/admin': typeof AuthWWorkspaceIdAdminRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_auth/w/$workspaceId/': typeof AuthWWorkspaceIdIndexRoute
  '/_auth/w/$workspaceId/c/$channelId': typeof AuthWWorkspaceIdCChannelIdRoute
  '/_auth/w/$workspaceId/d/$dmId': typeof AuthWWorkspaceIdDDmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pretentious'
    | '/profile'
    | '/pretentious/billing'
    | '/pretentious/landing'
    | '/pretentious/support'
    | '/pretentious/users'
    | '/theme/import'
    | '/pretentious/'
    | '/profile/connections'
    | '/w/$workspaceId/admin'
    | '/api/public/payments/webhook'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/c/$channelId'
    | '/w/$workspaceId/d/$dmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/profile'
    | '/pretentious/billing'
    | '/pretentious/landing'
    | '/pretentious/support'
    | '/pretentious/users'
    | '/theme/import'
    | '/pretentious'
    | '/profile/connections'
    | '/w/$workspaceId/admin'
    | '/api/public/payments/webhook'
    | '/w/$workspaceId'
    | '/w/$workspaceId/c/$channelId'
    | '/w/$workspaceId/d/$dmId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/login'
    | '/pretentious'
    | '/_auth/profile'
    | '/pretentious/billing'
    | '/pretentious/landing'
    | '/pretentious/support'
    | '/pretentious/users'
    | '/theme/import'
    | '/pretentious/'
    | '/_auth/profile/connections'
    | '/_auth/w/$workspaceId/admin'
    | '/api/public/payments/webhook'
    | '/_auth/w/$workspaceId/'
    | '/_auth/w/$workspaceId/c/$channelId'
    | '/_auth/w/$workspaceId/d/$dmId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  PretentiousRoute: typeof PretentiousRouteWithChildren
  ThemeImportRoute: typeof ThemeImportRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pretentious': {
      id: '/pretentious'
      path: '/pretentious'
      fullPath: '/pretentious'
      preLoaderRoute: typeof PretentiousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretentious/': {
      id: '/pretentious/'
      path: '/'
      fullPath: '/pretentious/'
      preLoaderRoute: typeof PretentiousIndexRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/theme/import': {
      id: '/theme/import'
      path: '/theme/import'
      fullPath: '/theme/import'
      preLoaderRoute: typeof ThemeImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretentious/users': {
      id: '/pretentious/users'
      path: '/users'
      fullPath: '/pretentious/users'
      preLoaderRoute: typeof PretentiousUsersRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/pretentious/support': {
      id: '/pretentious/support'
      path: '/support'
      fullPath: '/pretentious/support'
      preLoaderRoute: typeof PretentiousSupportRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/pretentious/landing': {
      id: '/pretentious/landing'
      path: '/landing'
      fullPath: '/pretentious/landing'
      preLoaderRoute: typeof PretentiousLandingRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/pretentious/billing': {
      id: '/pretentious/billing'
      path: '/billing'
      fullPath: '/pretentious/billing'
      preLoaderRoute: typeof PretentiousBillingRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/connections': {
      id: '/_auth/profile/connections'
      path: '/connections'
      fullPath: '/profile/connections'
      preLoaderRoute: typeof AuthProfileConnectionsRouteImport
      parentRoute: typeof AuthProfileRoute
    }
    '/_auth/w/$workspaceId/': {
      id: '/_auth/w/$workspaceId/'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AuthWWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/w/$workspaceId/admin': {
      id: '/_auth/w/$workspaceId/admin'
      path: '/w/$workspaceId/admin'
      fullPath: '/w/$workspaceId/admin'
      preLoaderRoute: typeof AuthWWorkspaceIdAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/w/$workspaceId/d/$dmId': {
      id: '/_auth/w/$workspaceId/d/$dmId'
      path: '/w/$workspaceId/d/$dmId'
      fullPath: '/w/$workspaceId/d/$dmId'
      preLoaderRoute: typeof AuthWWorkspaceIdDDmIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/w/$workspaceId/c/$channelId': {
      id: '/_auth/w/$workspaceId/c/$channelId'
      path: '/w/$workspaceId/c/$channelId'
      fullPath: '/w/$workspaceId/c/$channelId'
      preLoaderRoute: typeof AuthWWorkspaceIdCChannelIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthProfileRouteChildren {
  AuthProfileConnectionsRoute: typeof AuthProfileConnectionsRoute
}

const AuthProfileRouteChildren: AuthProfileRouteChildren = {
  AuthProfileConnectionsRoute: AuthProfileConnectionsRoute,
}

const AuthProfileRouteWithChildren = AuthProfileRoute._addFileChildren(
  AuthProfileRouteChildren,
)

interface AuthRouteChildren {
  AuthProfileRoute: typeof AuthProfileRouteWithChildren
  AuthWWorkspaceIdAdminRoute: typeof AuthWWorkspaceIdAdminRoute
  AuthWWorkspaceIdIndexRoute: typeof AuthWWorkspaceIdIndexRoute
  AuthWWorkspaceIdCChannelIdRoute: typeof AuthWWorkspaceIdCChannelIdRoute
  AuthWWorkspaceIdDDmIdRoute: typeof AuthWWorkspaceIdDDmIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRoute: AuthProfileRouteWithChildren,
  AuthWWorkspaceIdAdminRoute: AuthWWorkspaceIdAdminRoute,
  AuthWWorkspaceIdIndexRoute: AuthWWorkspaceIdIndexRoute,
  AuthWWorkspaceIdCChannelIdRoute: AuthWWorkspaceIdCChannelIdRoute,
  AuthWWorkspaceIdDDmIdRoute: AuthWWorkspaceIdDDmIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PretentiousRouteChildren {
  PretentiousBillingRoute: typeof PretentiousBillingRoute
  PretentiousLandingRoute: typeof PretentiousLandingRoute
  PretentiousSupportRoute: typeof PretentiousSupportRoute
  PretentiousUsersRoute: typeof PretentiousUsersRoute
  PretentiousIndexRoute: typeof PretentiousIndexRoute
}

const PretentiousRouteChildren: PretentiousRouteChildren = {
  PretentiousBillingRoute: PretentiousBillingRoute,
  PretentiousLandingRoute: PretentiousLandingRoute,
  PretentiousSupportRoute: PretentiousSupportRoute,
  PretentiousUsersRoute: PretentiousUsersRoute,
  PretentiousIndexRoute: PretentiousIndexRoute,
}

const PretentiousRouteWithChildren = PretentiousRoute._addFileChildren(
  PretentiousRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  PretentiousRoute: PretentiousRouteWithChildren,
  ThemeImportRoute: ThemeImportRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
