/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PretentiousRouteImport } from './routes/pretentious'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PretentiousIndexRouteImport } from './routes/pretentious.index'
import { Route as ThemeImportRouteImport } from './routes/theme.import'
import { Route as PretentiousUsersRouteImport } from './routes/pretentious.users'
import { Route as PretentiousSupportRouteImport } from './routes/pretentious.support'
import { Route as PretentiousLandingRouteImport } from './routes/pretentious.landing'
import { Route as PretentiousInvitesRouteImport } from './routes/pretentious.invites'
import { Route as PretentiousFlagsRouteImport } from './routes/pretentious.flags'
import { Route as PretentiousBillingRouteImport } from './routes/pretentious.billing'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthOnboardingIndexRouteImport } from './routes/_auth.onboarding.index'
import { Route as AuthProfileCreditsRouteImport } from './routes/_auth.profile.credits'
import { Route as AuthProfileConnectionsRouteImport } from './routes/_auth.profile.connections'
import { Route as AuthOnboardingTourRouteImport } from './routes/_auth.onboarding.tour'
import { Route as AuthOnboardingTeamRouteImport } from './routes/_auth.onboarding.team'
import { Route as AuthOnboardingProjectRouteImport } from './routes/_auth.onboarding.project'
import { Route as AuthOnboardingInvitesRouteImport } from './routes/_auth.onboarding.invites'
import { Route as AuthOnboardingFeaturesRouteImport } from './routes/_auth.onboarding.features'
import { Route as AuthOnboardingChannelRouteImport } from './routes/_auth.onboarding.channel'
import { Route as AuthWWorkspaceIdIndexRouteImport } from './routes/_auth.w.$workspaceId.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthWWorkspaceIdAdminRouteImport } from './routes/_auth.w.$workspaceId.admin'
import { Route as AuthWWorkspaceIdDDmIdRouteImport } from './routes/_auth.w.$workspaceId.d.$dmId'
import { Route as AuthWWorkspaceIdCChannelIdRouteImport } from './routes/_auth.w.$workspaceId.c.$channelId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PretentiousRoute = PretentiousRouteImport.update({
  id: '/pretentious',
  path: '/pretentious',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PretentiousIndexRoute = PretentiousIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PretentiousRoute,
} as any)
const ThemeImportRoute = ThemeImportRouteImport.update({
  id: '/theme/import',
  path: '/theme/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PretentiousUsersRoute = PretentiousUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PretentiousRoute,
} as any)
const PretentiousSupportRoute = PretentiousSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PretentiousRoute,
} as any)
const PretentiousLandingRoute = PretentiousLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => PretentiousRoute,
} as any)
const PretentiousInvitesRoute = PretentiousInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => PretentiousRoute,
} as any)
const PretentiousFlagsRoute = PretentiousFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => PretentiousRoute,
} as any)
const PretentiousBillingRoute = PretentiousBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PretentiousRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthProfileCreditsRoute = AuthProfileCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthProfileRoute,
} as any)
const AuthProfileConnectionsRoute = AuthProfileConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthProfileRoute,
} as any)
const AuthOnboardingTourRoute = AuthOnboardingTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingTeamRoute = AuthOnboardingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingProjectRoute = AuthOnboardingProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingInvitesRoute = AuthOnboardingInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingFeaturesRoute = AuthOnboardingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthOnboardingChannelRoute = AuthOnboardingChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => AuthOnboardingRoute,
} as any)
const AuthWWorkspaceIdIndexRoute = AuthWWorkspaceIdIndexRouteImport.update({
  id: '/w/$workspaceId/',
  path: '/w/$workspaceId/',
  getParentRoute: () => AuthRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthWWorkspaceIdAdminRoute = AuthWWorkspaceIdAdminRouteImport.update({
  id: '/w/$workspaceId/admin',
  path: '/w/$workspaceId/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWWorkspaceIdDDmIdRoute = AuthWWorkspaceIdDDmIdRouteImport.update({
  id: '/w/$workspaceId/d/$dmId',
  path: '/w/$workspaceId/d/$dmId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWWorkspaceIdCChannelIdRoute =
  AuthWWorkspaceIdCChannelIdRouteImport.update({
    id: '/w/$workspaceId/c/$channelId',
    path: '/w/$workspaceId/c/$channelId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/pretentious': typeof PretentiousRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding': typeof AuthOnboardingRouteWithChildren
  '/profile': typeof AuthProfileRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/pretentious/billing': typeof PretentiousBillingRoute
  '/pretentious/flags': typeof PretentiousFlagsRoute
  '/pretentious/invites': typeof PretentiousInvitesRoute
  '/pretentious/landing': typeof PretentiousLandingRoute
  '/pretentious/support': typeof PretentiousSupportRoute
  '/pretentious/users': typeof PretentiousUsersRoute
  '/theme/import': typeof ThemeImportRoute
  '/pretentious/': typeof PretentiousIndexRoute
  '/onboarding/channel': typeof AuthOnboardingChannelRoute
  '/onboarding/features': typeof AuthOnboardingFeaturesRoute
  '/onboarding/invites': typeof AuthOnboardingInvitesRoute
  '/onboarding/project': typeof AuthOnboardingProjectRoute
  '/onboarding/team': typeof AuthOnboardingTeamRoute
  '/onboarding/tour': typeof AuthOnboardingTourRoute
  '/profile/connections': typeof AuthProfileConnectionsRoute
  '/profile/credits': typeof AuthProfileCreditsRoute
  '/onboarding/': typeof AuthOnboardingIndexRoute
  '/w/$workspaceId/admin': typeof AuthWWorkspaceIdAdminRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/w/$workspaceId/': typeof AuthWWorkspaceIdIndexRoute
  '/w/$workspaceId/c/$channelId': typeof AuthWWorkspaceIdCChannelIdRoute
  '/w/$workspaceId/d/$dmId': typeof AuthWWorkspaceIdDDmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/profile': typeof AuthProfileRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/pretentious/billing': typeof PretentiousBillingRoute
  '/pretentious/flags': typeof PretentiousFlagsRoute
  '/pretentious/invites': typeof PretentiousInvitesRoute
  '/pretentious/landing': typeof PretentiousLandingRoute
  '/pretentious/support': typeof PretentiousSupportRoute
  '/pretentious/users': typeof PretentiousUsersRoute
  '/theme/import': typeof ThemeImportRoute
  '/pretentious': typeof PretentiousIndexRoute
  '/onboarding/channel': typeof AuthOnboardingChannelRoute
  '/onboarding/features': typeof AuthOnboardingFeaturesRoute
  '/onboarding/invites': typeof AuthOnboardingInvitesRoute
  '/onboarding/project': typeof AuthOnboardingProjectRoute
  '/onboarding/team': typeof AuthOnboardingTeamRoute
  '/onboarding/tour': typeof AuthOnboardingTourRoute
  '/profile/connections': typeof AuthProfileConnectionsRoute
  '/profile/credits': typeof AuthProfileCreditsRoute
  '/onboarding': typeof AuthOnboardingIndexRoute
  '/w/$workspaceId/admin': typeof AuthWWorkspaceIdAdminRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/w/$workspaceId': typeof AuthWWorkspaceIdIndexRoute
  '/w/$workspaceId/c/$channelId': typeof AuthWWorkspaceIdCChannelIdRoute
  '/w/$workspaceId/d/$dmId': typeof AuthWWorkspaceIdDDmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/pretentious': typeof PretentiousRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/_auth/onboarding': typeof AuthOnboardingRouteWithChildren
  '/_auth/profile': typeof AuthProfileRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/pretentious/billing': typeof PretentiousBillingRoute
  '/pretentious/flags': typeof PretentiousFlagsRoute
  '/pretentious/invites': typeof PretentiousInvitesRoute
  '/pretentious/landing': typeof PretentiousLandingRoute
  '/pretentious/support': typeof PretentiousSupportRoute
  '/pretentious/users': typeof PretentiousUsersRoute
  '/theme/import': typeof ThemeImportRoute
  '/pretentious/': typeof PretentiousIndexRoute
  '/_auth/onboarding/channel': typeof AuthOnboardingChannelRoute
  '/_auth/onboarding/features': typeof AuthOnboardingFeaturesRoute
  '/_auth/onboarding/invites': typeof AuthOnboardingInvitesRoute
  '/_auth/onboarding/project': typeof AuthOnboardingProjectRoute
  '/_auth/onboarding/team': typeof AuthOnboardingTeamRoute
  '/_auth/onboarding/tour': typeof AuthOnboardingTourRoute
  '/_auth/profile/connections': typeof AuthProfileConnectionsRoute
  '/_auth/profile/credits': typeof AuthProfileCreditsRoute
  '/_auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/_auth/w/$workspaceId/admin': typeof AuthWWorkspaceIdAdminRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_auth/w/$workspaceId/': typeof AuthWWorkspaceIdIndexRoute
  '/_auth/w/$workspaceId/c/$channelId': typeof AuthWWorkspaceIdCChannelIdRoute
  '/_auth/w/$workspaceId/d/$dmId': typeof AuthWWorkspaceIdDDmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pretentious'
    | '/reset-password'
    | '/verify-email'
    | '/welcome'
    | '/onboarding'
    | '/profile'
    | '/join/$token'
    | '/pretentious/billing'
    | '/pretentious/flags'
    | '/pretentious/invites'
    | '/pretentious/landing'
    | '/pretentious/support'
    | '/pretentious/users'
    | '/theme/import'
    | '/pretentious/'
    | '/onboarding/channel'
    | '/onboarding/features'
    | '/onboarding/invites'
    | '/onboarding/project'
    | '/onboarding/team'
    | '/onboarding/tour'
    | '/profile/connections'
    | '/profile/credits'
    | '/onboarding/'
    | '/w/$workspaceId/admin'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/c/$channelId'
    | '/w/$workspaceId/d/$dmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/welcome'
    | '/profile'
    | '/join/$token'
    | '/pretentious/billing'
    | '/pretentious/flags'
    | '/pretentious/invites'
    | '/pretentious/landing'
    | '/pretentious/support'
    | '/pretentious/users'
    | '/theme/import'
    | '/pretentious'
    | '/onboarding/channel'
    | '/onboarding/features'
    | '/onboarding/invites'
    | '/onboarding/project'
    | '/onboarding/team'
    | '/onboarding/tour'
    | '/profile/connections'
    | '/profile/credits'
    | '/onboarding'
    | '/w/$workspaceId/admin'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/w/$workspaceId'
    | '/w/$workspaceId/c/$channelId'
    | '/w/$workspaceId/d/$dmId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/login'
    | '/pretentious'
    | '/reset-password'
    | '/verify-email'
    | '/welcome'
    | '/_auth/onboarding'
    | '/_auth/profile'
    | '/join/$token'
    | '/pretentious/billing'
    | '/pretentious/flags'
    | '/pretentious/invites'
    | '/pretentious/landing'
    | '/pretentious/support'
    | '/pretentious/users'
    | '/theme/import'
    | '/pretentious/'
    | '/_auth/onboarding/channel'
    | '/_auth/onboarding/features'
    | '/_auth/onboarding/invites'
    | '/_auth/onboarding/project'
    | '/_auth/onboarding/team'
    | '/_auth/onboarding/tour'
    | '/_auth/profile/connections'
    | '/_auth/profile/credits'
    | '/_auth/onboarding/'
    | '/_auth/w/$workspaceId/admin'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/_auth/w/$workspaceId/'
    | '/_auth/w/$workspaceId/c/$channelId'
    | '/_auth/w/$workspaceId/d/$dmId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  PretentiousRoute: typeof PretentiousRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ThemeImportRoute: typeof ThemeImportRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretentious': {
      id: '/pretentious'
      path: '/pretentious'
      fullPath: '/pretentious'
      preLoaderRoute: typeof PretentiousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretentious/': {
      id: '/pretentious/'
      path: '/'
      fullPath: '/pretentious/'
      preLoaderRoute: typeof PretentiousIndexRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/theme/import': {
      id: '/theme/import'
      path: '/theme/import'
      fullPath: '/theme/import'
      preLoaderRoute: typeof ThemeImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretentious/users': {
      id: '/pretentious/users'
      path: '/users'
      fullPath: '/pretentious/users'
      preLoaderRoute: typeof PretentiousUsersRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/pretentious/support': {
      id: '/pretentious/support'
      path: '/support'
      fullPath: '/pretentious/support'
      preLoaderRoute: typeof PretentiousSupportRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/pretentious/landing': {
      id: '/pretentious/landing'
      path: '/landing'
      fullPath: '/pretentious/landing'
      preLoaderRoute: typeof PretentiousLandingRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/pretentious/invites': {
      id: '/pretentious/invites'
      path: '/invites'
      fullPath: '/pretentious/invites'
      preLoaderRoute: typeof PretentiousInvitesRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/pretentious/flags': {
      id: '/pretentious/flags'
      path: '/flags'
      fullPath: '/pretentious/flags'
      preLoaderRoute: typeof PretentiousFlagsRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/pretentious/billing': {
      id: '/pretentious/billing'
      path: '/billing'
      fullPath: '/pretentious/billing'
      preLoaderRoute: typeof PretentiousBillingRouteImport
      parentRoute: typeof PretentiousRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/': {
      id: '/_auth/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/profile/credits': {
      id: '/_auth/profile/credits'
      path: '/credits'
      fullPath: '/profile/credits'
      preLoaderRoute: typeof AuthProfileCreditsRouteImport
      parentRoute: typeof AuthProfileRoute
    }
    '/_auth/profile/connections': {
      id: '/_auth/profile/connections'
      path: '/connections'
      fullPath: '/profile/connections'
      preLoaderRoute: typeof AuthProfileConnectionsRouteImport
      parentRoute: typeof AuthProfileRoute
    }
    '/_auth/onboarding/tour': {
      id: '/_auth/onboarding/tour'
      path: '/tour'
      fullPath: '/onboarding/tour'
      preLoaderRoute: typeof AuthOnboardingTourRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/team': {
      id: '/_auth/onboarding/team'
      path: '/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof AuthOnboardingTeamRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/project': {
      id: '/_auth/onboarding/project'
      path: '/project'
      fullPath: '/onboarding/project'
      preLoaderRoute: typeof AuthOnboardingProjectRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/invites': {
      id: '/_auth/onboarding/invites'
      path: '/invites'
      fullPath: '/onboarding/invites'
      preLoaderRoute: typeof AuthOnboardingInvitesRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/features': {
      id: '/_auth/onboarding/features'
      path: '/features'
      fullPath: '/onboarding/features'
      preLoaderRoute: typeof AuthOnboardingFeaturesRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/onboarding/channel': {
      id: '/_auth/onboarding/channel'
      path: '/channel'
      fullPath: '/onboarding/channel'
      preLoaderRoute: typeof AuthOnboardingChannelRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/w/$workspaceId/': {
      id: '/_auth/w/$workspaceId/'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AuthWWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/w/$workspaceId/admin': {
      id: '/_auth/w/$workspaceId/admin'
      path: '/w/$workspaceId/admin'
      fullPath: '/w/$workspaceId/admin'
      preLoaderRoute: typeof AuthWWorkspaceIdAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/w/$workspaceId/d/$dmId': {
      id: '/_auth/w/$workspaceId/d/$dmId'
      path: '/w/$workspaceId/d/$dmId'
      fullPath: '/w/$workspaceId/d/$dmId'
      preLoaderRoute: typeof AuthWWorkspaceIdDDmIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/w/$workspaceId/c/$channelId': {
      id: '/_auth/w/$workspaceId/c/$channelId'
      path: '/w/$workspaceId/c/$channelId'
      fullPath: '/w/$workspaceId/c/$channelId'
      preLoaderRoute: typeof AuthWWorkspaceIdCChannelIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthOnboardingRouteChildren {
  AuthOnboardingChannelRoute: typeof AuthOnboardingChannelRoute
  AuthOnboardingFeaturesRoute: typeof AuthOnboardingFeaturesRoute
  AuthOnboardingInvitesRoute: typeof AuthOnboardingInvitesRoute
  AuthOnboardingProjectRoute: typeof AuthOnboardingProjectRoute
  AuthOnboardingTeamRoute: typeof AuthOnboardingTeamRoute
  AuthOnboardingTourRoute: typeof AuthOnboardingTourRoute
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
}

const AuthOnboardingRouteChildren: AuthOnboardingRouteChildren = {
  AuthOnboardingChannelRoute: AuthOnboardingChannelRoute,
  AuthOnboardingFeaturesRoute: AuthOnboardingFeaturesRoute,
  AuthOnboardingInvitesRoute: AuthOnboardingInvitesRoute,
  AuthOnboardingProjectRoute: AuthOnboardingProjectRoute,
  AuthOnboardingTeamRoute: AuthOnboardingTeamRoute,
  AuthOnboardingTourRoute: AuthOnboardingTourRoute,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
}

const AuthOnboardingRouteWithChildren = AuthOnboardingRoute._addFileChildren(
  AuthOnboardingRouteChildren,
)

interface AuthProfileRouteChildren {
  AuthProfileConnectionsRoute: typeof AuthProfileConnectionsRoute
  AuthProfileCreditsRoute: typeof AuthProfileCreditsRoute
}

const AuthProfileRouteChildren: AuthProfileRouteChildren = {
  AuthProfileConnectionsRoute: AuthProfileConnectionsRoute,
  AuthProfileCreditsRoute: AuthProfileCreditsRoute,
}

const AuthProfileRouteWithChildren = AuthProfileRoute._addFileChildren(
  AuthProfileRouteChildren,
)

interface AuthRouteChildren {
  AuthOnboardingRoute: typeof AuthOnboardingRouteWithChildren
  AuthProfileRoute: typeof AuthProfileRouteWithChildren
  AuthWWorkspaceIdAdminRoute: typeof AuthWWorkspaceIdAdminRoute
  AuthWWorkspaceIdIndexRoute: typeof AuthWWorkspaceIdIndexRoute
  AuthWWorkspaceIdCChannelIdRoute: typeof AuthWWorkspaceIdCChannelIdRoute
  AuthWWorkspaceIdDDmIdRoute: typeof AuthWWorkspaceIdDDmIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOnboardingRoute: AuthOnboardingRouteWithChildren,
  AuthProfileRoute: AuthProfileRouteWithChildren,
  AuthWWorkspaceIdAdminRoute: AuthWWorkspaceIdAdminRoute,
  AuthWWorkspaceIdIndexRoute: AuthWWorkspaceIdIndexRoute,
  AuthWWorkspaceIdCChannelIdRoute: AuthWWorkspaceIdCChannelIdRoute,
  AuthWWorkspaceIdDDmIdRoute: AuthWWorkspaceIdDDmIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PretentiousRouteChildren {
  PretentiousBillingRoute: typeof PretentiousBillingRoute
  PretentiousFlagsRoute: typeof PretentiousFlagsRoute
  PretentiousInvitesRoute: typeof PretentiousInvitesRoute
  PretentiousLandingRoute: typeof PretentiousLandingRoute
  PretentiousSupportRoute: typeof PretentiousSupportRoute
  PretentiousUsersRoute: typeof PretentiousUsersRoute
  PretentiousIndexRoute: typeof PretentiousIndexRoute
}

const PretentiousRouteChildren: PretentiousRouteChildren = {
  PretentiousBillingRoute: PretentiousBillingRoute,
  PretentiousFlagsRoute: PretentiousFlagsRoute,
  PretentiousInvitesRoute: PretentiousInvitesRoute,
  PretentiousLandingRoute: PretentiousLandingRoute,
  PretentiousSupportRoute: PretentiousSupportRoute,
  PretentiousUsersRoute: PretentiousUsersRoute,
  PretentiousIndexRoute: PretentiousIndexRoute,
}

const PretentiousRouteWithChildren = PretentiousRoute._addFileChildren(
  PretentiousRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  PretentiousRoute: PretentiousRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
  JoinTokenRoute: JoinTokenRoute,
  ThemeImportRoute: ThemeImportRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
